In [219]:
import numpy as np
import pandas as pd

## Exercise 1

In [220]:
link = "https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data"
columns = ["symboling",
    "normalized-losses",
    "make",
    "fuel-type",
    "aspiration",
    "num-of-doors",
    "body-style",
    "drive-wheels",
    "engine-location",
    "wheel-base",
    "length",
    "width",
    "height",
    "curb-weight",
    "engine-type",
    "num-of-cylinders",
    "engine-size",
    "fuel-system",
    "bore",
    "stroke",
    "compression-ratio",
    "horsepower",
    "peak-rpm",
    "city-mpg",
    "highway-mpg",
    "price"]
df = pd.read_csv(link, names=columns)
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [221]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       205 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               205 non-null    object
 19  stroke             205 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    object
 22  peak-rpm           205 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [222]:
# Check values in object type columns
pd.set_option("max_colwidth", None)

df_value = pd.DataFrame(columns=['column', 'value'])

for i in df.columns:
    if df[i].dtype == 'O':
        temp = pd.DataFrame([[i, df[i].unique()]], columns=['column', 'value'])
        df_value = df_value.append(temp)
        
df_value

,column,value
0,normalized-losses,"[?, 164, 158, 192, 188, 121, 98, 81, 118, 148, 110, 145, 137, 101, 78, 106, 85, 107, 104, 113, 150, 129, 115, 93, 142, 161, 153, 125, 128, 122, 103, 168, 108, 194, 231, 119, 154, 74, 186, 83, 102, 89, 87, 77, 91, 134, 65, 197, 90, 94, 256, 95]"
0,make,"[alfa-romero, audi, bmw, chevrolet, dodge, honda, isuzu, jaguar, mazda, mercedes-benz, mercury, mitsubishi, nissan, peugot, plymouth, porsche, renault, saab, subaru, toyota, volkswagen, volvo]"
0,fuel-type,"[gas, diesel]"
0,aspiration,"[std, turbo]"
0,num-of-doors,"[two, four, ?]"
0,body-style,"[convertible, hatchback, sedan, wagon, hardtop]"
0,drive-wheels,"[rwd, fwd, 4wd]"
0,engine-location,"[front, rear]"
0,engine-type,"[dohc, ohcv, ohc, l, rotor, ohcf, dohcv]"
0,num-of-cylinders,"[four, six, five, three, twelve, two, eight]"
0,fuel-system,"[mpfi, 2bbl, mfi, 1bbl, spfi, 4bbl, idi, spdi]"
0,bore,"[3.47, 2.68, 3.19, 3.13, 3.50, 3.31, 3.62, 2.91, 3.03, 2.97, 3.34, 3.60, 2.92, 3.15, 3.43, 3.63, 3.54, 3.08, ?, 3.39, 3.76, 3.58, 3.46, 3.80, 3.78, 3.17, 3.35, 3.59, 2.99, 3.33, 3.70, 3.61, 3.94, 3.74, 2.54, 3.05, 3.27, 3.24, 3.01]"
0,stroke,"[2.68, 3.47, 3.40, 2.80, 3.19, 3.39, 3.03, 3.11, 3.23, 3.46, 3.90, 3.41, 3.07, 3.58, 4.17, 2.76, 3.15, ?, 3.16, 3.64, 3.10, 3.35, 3.12, 3.86, 3.29, 3.27, 3.52, 2.19, 3.21, 2.90, 2.07, 2.36, 2.64, 3.08, 3.50, 3.54, 2.87]"
0,horsepower,"[111, 154, 102, 115, 110, 140, 160, 101, 121, 182, 48, 70, 68, 88, 145, 58, 76, 60, 86, 100, 78, 90, 176, 262, 135, 84, 64, 120, 72, 123, 155, 184, 175, 116, 69, 55, 97, 152, 200, 95, 142, 143, 207, 288, ?, 73, 82, 94, 62, 56, 112, 92, 161, 156, 52, 85, 114, 162, 134, 106]"
0,peak-rpm,"[5000, 5500, 5800, 4250, 5400, 5100, 4800, 6000, 4750, 4650, 4200, 4350, 4500, 5200, 4150, 5600, 5900, 5750, ?, 5250, 4900, 4400, 6600, 5300]"
0,price,"[13495, 16500, 13950, 17450, 15250, 17710, 18920, 23875, ?, 16430, 16925, 20970, 21105, 24565, 30760, 41315, 36880, 5151, 6295, 6575, 5572, 6377, 7957, 6229, 6692, 7609, 8558, 8921, 12964, 6479, 6855, 5399, 6529, 7129, 7295, 7895, 9095, 8845, 10295, 12945, 10345, 6785, 11048, 32250, 35550, 36000, 5195, 6095, 6795, 6695, 7395, 10945, 11845, 13645, 15645, 8495, 10595, 10245, 10795, 11245, 18280, 18344, 25552, 28248, 28176, 31600, 34184, 35056, 40960, 45400, 16503, 5389, 6189, 6669, 7689, 9959, 8499, 12629, 14869, 14489, 6989, 8189, 9279, 5499, 7099, 6649, 6849, 7349, 7299, 7799, 7499, 7999, 8249, 8949, 9549, 13499, 14399, 17199, 19699, 18399, ...]"

In [223]:
# Replace "?" with null
columns = ['normalized-losses', 'num-of-doors', 'bore', 'stroke', 'horsepower', 'peak-rpm', 'price']
df[columns] = df[columns].replace("?", np.nan)

In [224]:
# Change column type to numberical:
columns = ['normalized-losses', 'bore', 'stroke', 'horsepower', 'peak-rpm', 'price']
df[columns] = df[columns].astype('float32')

In [225]:
columns = ['num-of-doors', 'num-of-cylinders']
dct = {
    'two' : 2,
    'three' : 3,
    'four' : 4,
    'five' : 5,
    'six' : 6,
    'eight' : 8,
    'twelve' : 12
}
df[columns] = df[columns].replace(dct)

In [226]:
# Check correlation of all numeric columns to price
df.corr()['price']

symboling           -0.082391
normalized-losses    0.203254
num-of-doors         0.046532
wheel-base           0.584642
length               0.690628
width                0.751265
height               0.135486
curb-weight          0.834415
num-of-cylinders     0.708645
engine-size          0.872335
bore                 0.543436
stroke               0.082310
compression-ratio    0.071107
horsepower           0.810533
peak-rpm            -0.101649
city-mpg            -0.686571
highway-mpg         -0.704692
price                1.000000
Name: price, dtype: float64

In [227]:
# Choose ones whose absolute value are over 0.5
columns = ['normalized-losses', 'length', 'width', 'curb-weight', 'num-of-cylinders', 'engine-size', 'bore', 'horsepower', 'city-mpg', 
          'highway-mpg', 'price']
df = df[columns]

In [228]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   normalized-losses  164 non-null    float32
 1   length             205 non-null    float64
 2   width              205 non-null    float64
 3   curb-weight        205 non-null    int64
 4   num-of-cylinders   205 non-null    int64
 5   engine-size        205 non-null    int64
 6   bore               201 non-null    float32
 7   horsepower         203 non-null    float32
 8   city-mpg           205 non-null    int64
 9   highway-mpg        205 non-null    int64
 10  price              201 non-null    float32
dtypes: float32(4), float64(2), int64(5)
memory usage: 14.5 KB

In [229]:
# Drop null from price column
df = df[~df['price'].isna()]

In [230]:
columns = ['normalized-losses', 'bore', 'horsepower']

for i in columns:
    df[i] = df[i].fillna(df[i].mean())

In [231]:
# Build model (without scaling)
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

from sklearn.model_selection import train_test_split

In [232]:
X = df.drop(['price'], axis=1)
y = df['price']

Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, random_state=1)

In [233]:
# Linear Regression
lin_model = LinearRegression(fit_intercept=True)

lin_model.fit(Xtrain, ytrain)
lin_model.score(Xtest, ytest)

0.7490233198211884

In [234]:
# Predict test dataset
yprd = lin_model.predict(Xtest)
result_df = pd.DataFrame()
result_df['test'] = ytest
result_df['predict'] = yprd
result_df['predict'] = round(result_df['predict'])
result_df['difference'] = round(result_df['predict']/result_df['test'] * 100,2)
result_df

        test  predict  difference
100   9549.0  11880.0      124.41
120   6229.0   6384.0      102.49
62   10245.0  12143.0      118.53
36    7295.0   6083.0       83.39
169   9989.0  16259.0      162.77
151   6338.0   5900.0       93.09
29   12964.0  19701.0      151.97
81    8499.0  12182.0      143.33
4    17450.0  15313.0       87.75
19    6295.0   5198.0       82.57
173   8948.0  11872.0      132.68
35    7295.0   6100.0       83.62
167   8449.0  16243.0      192.25
12   20970.0  17765.0       84.72
149  11694.0  10029.0       85.76
115  16630.0  14604.0       87.82
30    6479.0   4975.0       76.79
203  22470.0  15661.0       69.70
96    7499.0   6546.0       87.29
185   8195.0  10120.0      123.49
39    8845.0   9843.0      111.28
163   8058.0   7076.0       87.81
17   36880.0  29431.0       79.80
111  15580.0  14510.0       93.13
32    5399.0   3631.0       67.25
47   32250.0  34680.0      107.53
170  11199.0  16440.0      146.80
50    5195.0   4908.0       94.48
176  10898.0  12077.0      110.82
97    7999.0   6388.0       79.86
194  12940.0  16266.0      125.70
28    8921.0  11518.0      129.11
41   12945.0  10417.0       80.47
92    6849.0   6499.0       94.89
179  15998.0  22116.0      138.24
136  18150.0  16536.0       91.11
87    9279.0  12207.0      131.56
142   7775.0   9150.0      117.68
101  13499.0  21969.0      162.75
70   31600.0  24061.0       76.14
192  13845.0   8514.0       61.50
113  16695.0  14226.0       85.21
125  22018.0  21154.0       96.08
61   10595.0  12181.0      114.97
15   30760.0  27048.0       87.93
59    8845.0  12181.0      137.72
20    6575.0   5069.0       77.10
54    7395.0   6178.0       83.54
40   10295.0   8292.0       80.54
106  18399.0  24056.0      130.75
131   9895.0  14998.0      151.57

In [235]:
# Polynomial regression
from sklearn.preprocessing import PolynomialFeatures
poly_model = PolynomialFeatures(degree=2)
Xtrain_poly = poly_model.fit_transform(Xtrain)

pol_model = LinearRegression()
pol_model.fit(Xtrain_poly, ytrain)

LinearRegression()

In [236]:
# Test
Xtest_poly = poly_model.fit_transform(Xtest)
pol_model.score(Xtest_poly, ytest)

0.4729193355343583

In [237]:
# Predict test dataset
yprd = pol_model.predict(Xtest_poly)
result_df = pd.DataFrame()
result_df['test'] = ytest
result_df['predict'] = yprd
result_df['predict'] = round(result_df['predict'])
result_df['difference'] = round(result_df['predict']/result_df['test'] * 100,2)
result_df

        test  predict  difference
100   9549.0   6260.0       65.56
120   6229.0   6677.0      107.19
62   10245.0   7457.0       72.79
36    7295.0   7896.0      108.24
169   9989.0   8355.0       83.64
151   6338.0   6941.0      109.51
29   12964.0  12430.0       95.88
81    8499.0   8862.0      104.27
4    17450.0  17877.0      102.45
19    6295.0   3973.0       63.11
173   8948.0   3041.0       33.99
35    7295.0   7975.0      109.32
167   8449.0   8074.0       95.56
12   20970.0  27710.0      132.14
149  11694.0   6638.0       56.76
115  16630.0  14387.0       86.51
30    6479.0  -7241.0     -111.76
203  22470.0   7301.0       32.49
96    7499.0   7395.0       98.61
185   8195.0   7078.0       86.37
39    8845.0   8962.0      101.32
163   8058.0   8544.0      106.03
17   36880.0  31611.0       85.71
111  15580.0  14536.0       93.30
32    5399.0  10950.0      202.82
47   32250.0  32884.0      101.97
170  11199.0  11429.0      102.05
50    5195.0   -261.0       -5.02
176  10898.0   5830.0       53.50
97    7999.0  10405.0      130.08
194  12940.0  14514.0      112.16
28    8921.0   9720.0      108.96
41   12945.0   9210.0       71.15
92    6849.0   7181.0      104.85
179  15998.0  22091.0      138.09
136  18150.0  19286.0      106.26
87    9279.0  13852.0      149.28
142   7775.0   6736.0       86.64
101  13499.0  25270.0      187.20
70   31600.0  23687.0       74.96
192  13845.0   9247.0       66.79
113  16695.0    975.0        5.84
125  22018.0  34808.0      158.09
61   10595.0   7587.0       71.61
15   30760.0  34677.0      112.73
59    8845.0   7587.0       85.78
20    6575.0   6593.0      100.27
54    7395.0  10065.0      136.11
40   10295.0   9376.0       91.07
106  18399.0  22075.0      119.98
131   9895.0   7981.0       80.66